using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ZintTest
{
    public enum EncodingMode : int { DATA_MODE, UNICODE_MODE, GS1_MODE, KANJI_MODE, SJIS_MODE };
    public enum BarcodeTypes : int
    {
        NONE,
        CODE11,
        C25MATRIX,
        C25INTER,
        C25IATA,
        C25LOGIC,
        C25IND,
        CODE39,
        EXCODE39,
        EANX,
        EAN128,
        CODABAR,
        CODE128,
        DPLEIT,
        DPIDENT,
        CODE16K,
        CODE49,
        CODE93,
        FLAT,
        RSS14,
        RSS_LTD,
        RSS_EXP,
        TELEPEN,
        UPCA,
        UPCE,
        POSTNET,
        MSI_PLESSEY,
        FIM,
        LOGMARS,
        PHARMA,
        PZN,
        PHARMA_TWO,
        PDF417,
        PDF417TRUNC,
        MAXICODE,
        QRCODE,
        CODE128B,
        AUSPOST,
        AUSREPLY,
        AUSROUTE,
        AUSREDIRECT,
        ISBNX,
        RM4SCC,
        DATAMATRIX,
        EAN14,
        CODABLOCKF,
        NVE18,
        JAPANPOST,
        KOREAPOST,
        RSS14STACK,
        RSS14STACK_OMNI,
        RSS_EXPSTACK,
        PLANET,
        MICROPDF417,
        ONECODE,
        PLESSEY,
        TELEPEN_NUM,
        ITF14,
        KIX,
        AZTEC,
        DAFT,
        MICROQR,
        HIBC_128,
        HIBC_39,
        HIBC_DM,
        HIBC_QR,
        HIBC_PDF,
        HIBC_MICPDF,
        HIBC_BLOCKF,
        HIBC_AZTEC,
        AZRUNE,
        CODE32,
        EANX_CC,
        EAN128_CC,
        RSS14_CC,
        RSS_LTD_CC,
        RSS_EXP_CC,
        UPCA_CC,
        UPCE_CC,
        RSS14STACK_CC,
        RSS14_OMNI_CC,
        RSS_EXPSTACK_CC,
        CHANNEL,
        CODEONE,
        GRIDMATRIX
    };
}
